osx_image: xcode8.1
language: objective-c

install:
  - pod install --project-directory=./Tests/iOS
  - pod install --project-directory=./Tests/Mac

script:
  - set -o pipefail
  - xcodebuild -workspace ./Tests/iOS/CocoaAsyncSocket.xcworkspace -scheme CocoaAsyncSocketTestsiOS -sdk iphonesimulator -destination 'name=iPhone 6' test | xcpretty -c
  - xcodebuild -workspace ./Tests/Mac/CocoaAsyncSocket.xcworkspace -scheme CocoaAsyncSocketTestsMac -sdk macosx -destination 'platform=OS X,arch=x86_64' test | xcpretty -c
  - xcodebuild -project CocoaAsyncSocket.xcodeproj -scheme "iOS Framework" -sdk iphonesimulator -destination 'name=iPhone 6' build | xcpretty -c
  - xcodebuild -project CocoaAsyncSocket.xcodeproj -scheme "Mac Framework" -sdk macosx -destination 'platform=OS X,arch=x86_64' build | xcpretty -c
