osx_image: xcode11.3
language: objective-c

install:
  - bundle install
  - cd Tests
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Mac
  - cd ../

script:
  - export IOS_VERSION="13.3"
  - bash Tests/test-all.sh
  - swift build
  - swift test
  - bundle exec pod lib lint
